//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbConnDemo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int Id { get; set; }
        public int CourseCode { get; set; }
        public string Name { get; set; }
        public int Credit { get; set; }
        public string Type { get; set; }
        public int DeptId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
