//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int mId { get; set; }
        public string mname { get; set; }
        public string mstatus { get; set; }
        public int pId { get; set; }
    
        public virtual project project { get; set; }
    }
}
